package main

import (
	"log"
	"net/http"

	"github.com/gaanon/gorecipes_v2/config"
	_ "github.com/gaanon/gorecipes_v2/docs" // docs is generated by Swag CLI
	"github.com/gaanon/gorecipes_v2/handlers"
	"github.com/gaanon/gorecipes_v2/store"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title GoRecipes API
// @version v1
// @description This is the API for the GoRecipes application, allowing users to manage and discover cooking recipes.
// @termsOfService http://example.com/terms/
// @contact.name API Support Team
// @contact.url http://www.example.com/support
// @contact.email support@example.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /api/v1
// @schemes http https
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	// Load configuration
	dbCfg := config.DefaultDBConfig()
	// Production reminder: Load credentials securely, e.g., from environment variables or a config file.
	// Ensure config.go has your actual DB credentials if you haven't updated it yet.

	// Initialize database pool
	dbPool, err := store.NewDBPool(dbCfg)
	if err != nil {
		log.Fatalf("Failed to initialize database connection: %v", err)
	}
	defer dbPool.Close() // Ensure the pool is closed when the application exits

	// Initialize store
	recipeStore := store.NewRecipeStore(dbPool)

	// Initialize handlers
	recipeHandler := handlers.NewRecipeHandler(recipeStore)

	// Initialize Gin router
	router := gin.Default()

	// Health check endpoint
	router.GET("/ping", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "pong",
		})
	})

	// Recipe routes
	apiV1 := router.Group("/api/v1") // Group routes under /api/v1
	{
		recipesGroup := apiV1.Group("/recipes")
		{
			recipesGroup.POST("", recipeHandler.CreateRecipe)
			recipesGroup.GET("", recipeHandler.ListRecipes)
			recipesGroup.GET("/:id", recipeHandler.GetRecipe)
			recipesGroup.PUT("/:id", recipeHandler.UpdateRecipe)
			recipesGroup.DELETE("/:id", recipeHandler.DeleteRecipe)
		}
	}

	// Swagger endpoint
	// URL: http://localhost:8080/swagger/index.html
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server
	serverAddr := ":8080" // Make this configurable later
	log.Printf("Server starting on %s", serverAddr)
	if err := router.Run(serverAddr); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
